package com.sheepapps.englishvalley.network

import kotlinx.coroutines.*

class Repository(private val api: FactApi) {

    private val parentJob = SupervisorJob()
    private val coroutineScope = CoroutineScope(parentJob + Dispatchers.Default)

    fun getFacts(): List<Fact> {
        return try {
            runBlocking {
                withContext(coroutineScope.coroutineContext) {
                    mapFacts(api.getFacts(7))
                }
            }
        } catch (e: Exception) {
            listOf(Fact( "Connection error occurred. This fact is autogenerated :)"))
        }
    }

    private fun mapFacts(facts: List<Fact>) = facts.map {
        Fact(it.text)
    }

}